sudo: required

env:
  global:
    - THRIFT_VERSION=0.9.3

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev
      - libboost-program-options-dev
      - libevent-dev
      - libssl-dev

before_install:
  - bash scripts/install-thrift.sh

notifications:
  email: false
