sudo: false

env:
  global:
    - THRIFT_VERSION=0.9.3

language: java

jdk:
  - oraclejdk8

before_install:
  - wget http://www.eu.apache.org/dist/thrift/${THRIFT_VERSION}/thrift-${THRIFT_VERSION}.tar.gz -O /tmp/thrift.tar.gz
  - tar -xvzf /tmp/thrift.tar.gz
  - cd /tmp/thrift-${THRIFT_VERSION} && ./configure && ./configure

notifications:
  email: false
